export const ROUTES = {
  HOME: '/',
  NEWS: '/news',
  FAQ: '/faq',
  ABOUT: '/about',
  TOP_100: '/top-100',
  ALBUM_VALUE: '/albumvalue',
  RATING: '/rating',
  RZT_AWARDS: '/rztawards',
  FRESHMEN: '/freshmen',
  PLAYLISTS: '/playlists',
  AUTHOR_LIKES: '/author-likes',
  AUTHOR_COMMENTS: '/author-comments',
  AUTHORS_VERIFIED: '/authors-verified',
  AUTHORS: '/authors',
  AUTHOR: '/author/:id',
  REVIEWS: '/reviews',
  RELEASES: '/releases',
  RELEASE: '/release/:id',
  CREATE_RELEASE: '/create-release',
  CONTACT: '/contact'
}; 