export const ROUTES = {
  HOME: '/',
  NEWS: '/news',
  FAQ: '/faq',
  ABOUT: '/about',
  TOP_100: '/top-100',
  ALBUM_VALUE: '/albumvalue',
  RATING: '/rating',
  RZT_AWARDS: '/rztawards',
  FRESHMEN: '/freshmen',
  PLAYLISTS: '/playlists',
  AUTHOR_LIKES: '/author-likes',
  AUTHOR_COMMENTS: '/author-comments',
  AUTHORS_VERIFIED: '/authors-verified',
  AUTHORS: '/authors',
  AUTHOR: '/author/:id',
  REVIEWS: '/reviews',
  REVIEW: '/reviews/:reviewId',
  RELEASES: '/releases',
  RELEASE: '/release/:id',
  CREATE_RELEASE: '/create-release',
  MODERATOR_CREATE_RELEASE: '/moderator/create-release',
  MODERATOR_REPORTS: '/moderator/reports',
  CONTACT: '/contact',
  USER_AGREEMENT: '/user-agreement',
  PRIVACY_POLICY: '/policy-personal'
}; 